export const PERMISSIONS = {
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DISABLE: "USER_DISABLE",
  USER_ASSIGN_ROLE: "USER_ASSIGN_ROLE",
  USER_RESET_PASSWORD: "USER_RESET_PASSWORD",
  ROLE_VIEW: "ROLE_VIEW",
  ROLE_MANAGE: "ROLE_MANAGE",
  ASSIGNMENT_VIEW_ALL: "ASSIGNMENT_VIEW_ALL",
  ASSIGNMENT_VIEW_OWN: "ASSIGNMENT_VIEW_OWN",
  ASSIGNMENT_CREATE: "ASSIGNMENT_CREATE",
  ASSIGNMENT_UPDATE: "ASSIGNMENT_UPDATE",
  ASSIGNMENT_CANCEL: "ASSIGNMENT_CANCEL",
  ASSIGNMENT_COMPLETE: "ASSIGNMENT_COMPLETE",
  PERSON_VIEW: "PERSON_VIEW",
  PERSON_CREATE_IN_ASSIGNMENT: "PERSON_CREATE_IN_ASSIGNMENT",
  PERSON_UPDATE_IN_ASSIGNMENT: "PERSON_UPDATE_IN_ASSIGNMENT",
  PERSON_DELETE: "PERSON_DELETE",
  PERSON_CHANGE_EXTERNAL_ID: "PERSON_CHANGE_EXTERNAL_ID",
  RELATION_VIEW: "RELATION_VIEW",
  RELATION_CREATE_IN_ASSIGNMENT: "RELATION_CREATE_IN_ASSIGNMENT",
  RELATION_UPDATE_IN_ASSIGNMENT: "RELATION_UPDATE_IN_ASSIGNMENT",
  RELATION_DELETE_IN_ASSIGNMENT: "RELATION_DELETE_IN_ASSIGNMENT",
  HOMELAND_VIEW: "HOMELAND_VIEW",
  HOMELAND_CREATE: "HOMELAND_CREATE",
  PLACE_VIEW: "PLACE_VIEW",
  PLACE_CREATE: "PLACE_CREATE",
  PLACE_UPDATE: "PLACE_UPDATE",
  PLACE_DELETE: "PLACE_DELETE",
  REVIEW_QUEUE_VIEW: "REVIEW_QUEUE_VIEW",
  PERSON_REVIEW_VIEW: "PERSON_REVIEW_VIEW",
  PERSON_APPROVE: "PERSON_APPROVE",
  PERSON_REQUEST_CHANGES: "PERSON_REQUEST_CHANGES",
  PERSON_REVIEW_COMMENT: "PERSON_REVIEW_COMMENT",
  PERSON_APPROVAL_REVOKE: "PERSON_APPROVAL_REVOKE",
} as const;

export type PermissionCode =
  (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

export const ROLE_CODES = {
  MANAGER: "MANAGER",
  CONTROLLER: "CONTROLLER",
  RESEARCHER: "RESEARCHER",
} as const;

export type RoleCode = (typeof ROLE_CODES)[keyof typeof ROLE_CODES];

export function hasPermission(
  permissions: readonly string[],
  permission: PermissionCode,
) {
  return permissions.includes(permission);
}
